### ISSUE TITLE
Cannot import name protocols

### ISSUE THREAD

**Issue by nguillermin** [pculture/mirovideoconverter3#27]
OS X 10.10.5, homebrew-installed Python 2.7.10 

```
$ python2.7 test/runtests.py 
Traceback (most recent call last):
  File "test/runtests.py", line 8, in <module>
    from test_video import *
  File "/Users/megablanc/Developer/mirovideoconverter3/test/test_video.py", line 8, in <module>
    from mvc import video
  File "test/../mvc/__init__.py", line 5, in <module>
    from mvc import conversion
  File "test/../mvc/conversion.py", line 12, in <module>
    from mvc.video import get_thumbnail_synchronous
  File "test/../mvc/video.py", line 8, in <module>
    from mvc.widgets import idle_add
  File "test/../mvc/widgets/__init__.py", line 7, in <module>
    from .osx import widgetset
  File "test/../mvc/widgets/osx/widgetset.py", line 45, in <module>
    from .layout import VBox, HBox, Alignment, Table, Scroller, Expander, TabContainer, DetachedWindowHolder
  File "test/../mvc/widgets/osx/layout.py", line 49, in <module>
    import tableview
  File "test/../mvc/widgets/osx/tableview.py", line 50, in <module>
    import tablemodel
  File "test/../mvc/widgets/osx/tablemodel.py", line 34, in <module>
    from AppKit import (NSDragOperationNone, NSDragOperationAll, NSTableViewDropOn,
ImportError: cannot import name protocols
```

The full line at tablemodel.py:34 is

```
from AppKit import (NSDragOperationNone, NSDragOperationAll, NSTableViewDropOn,
                     NSOutlineViewDropOnItemIndex, protocols)
```

I've tried importing NSDragOperationNone, NSDragOperationAll, NSTableViewDropOn, NSOutlineViewDropOnItemIndex individually from python interpreter with no issue. `from AppKit import protocols` fails.

**Comment by Rudloff** [comment]
Same problem on OSX 10.11.

**Comment by ronaldoussoren** [comment]
The import of "protocols" is not necessary with recent versions of PyObjC. When using explicit protocols use `objc.protocolNamed("name")`, and it is never necessary to use an informal protocol object (which is why framework wrappers no longer explose those)
